_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 6411cce0-5f22-482c-b1e3-8d5a6b770905
name: 'Silvi Mix Request App'
mail: website@mix.silvi.app
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
